base: &base
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  database: fae_dummy
  username: root
  password:
  host: localhost

development:
  <<: *base

test:
  <<: *base
  database: fae_dummy_test

production:
  <<: *base